anguage: node_js
node_js:
  - "14"
services:
  - docker

cache: yarn

install:
  - yarn

script:
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t changs/react-ts-boilerplate:latest .
  - docker push changs/react-ts-boilerplate:latest
